JPERF-941: Update locks after plugin bump
The `gradle-release` plugin was bumped to fix release.
But I forgot to handle dep locks, so `dokkaHtml` task was failing with:
```
java.lang.NoClassDefFoundError: kotlin/UByte
```

Dokka classpaths are excluded from manual conflict resolution and locks.
Locks rewritten by `./gradlew dep --write-locks`.
The `dokkaHtml` task is fixed.