JPERF-382: Require idempotent copy from io
Otherwise the S3 object download retries always fail with:
```
2019-02-05T15:43:32,934Z DEBUG <pool-2-thread-3> {cohort=c4.8xlarge, 2 nodes, run 1} [c4.8xlarge, 2 nodes, run 1] [com.atlassian.performance.tools.jvmtasks.api.IdempotentAction.Companion] Stacktrace for #2 failed attempt of download jpt-8c31d457-3165-4d30-8a47-acac35c01d68/jira-node-1/access_log.2019-02-05
java.lang.RuntimeException: /Users/Dagguh/Work/apt/jira-hardware-exploration/build/jpt-workspace/QUICK-53-fixed-rte/c4.8xlarge/nodes/2/runs/1/c4.8xlarge, 2 nodes, run 1/jira-node-1/access_log.2019-02-05 already exists and is not a directory
        at com.atlassian.performance.tools.io.api.DirectoriesKt.ensureDirectory(Directories.kt:38) ~[virtual-users.jar:?]
        at com.atlassian.performance.tools.io.api.DirectoriesKt.copy(Directories.kt:64) ~[virtual-users.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage.downloadObject(Storage.kt:122) ~[aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage.access$downloadObject(Storage.kt:18) ~[aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage$download$$inlined$map$lambda$1.invoke(Storage.kt:100) ~[aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage$download$$inlined$map$lambda$1.invoke(Storage.kt:18) ~[aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.jvmtasks.api.IdempotentAction.retry(IdempotentAction.kt:27) [virtual-users.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage.download(Storage.kt:104) [aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.aws.api.Storage.download(Storage.kt:85) [aws-resources-1.3.4-SNAPSHOT.jar:?]
        at com.atlassian.performance.tools.awsinfrastructure.api.Infrastructure.downloadResults(Infrastructure.kt:66) [aws-infrastructure-2.1.0.jar:?]
        at com.atlassian.performance.tools.jiraperformancetests.api.ProvisioningPerformanceTest.run(ProvisioningPerformanceTest.kt:59) [jira-performance-tests-3.0.0.jar:?]
        at com.atlassian.performance.tools.jiraperformancetests.api.ProvisioningPerformanceTest$runAsync$1.invoke(ProvisioningPerformanceTest.kt:35) [jira-performance-tests-3.0.0.jar:?]
        at com.atlassian.performance.tools.jiraperformancetests.api.ProvisioningPerformanceTest$runAsync$1.invoke(ProvisioningPerformanceTest.kt:22) [jira-performance-tests-3.0.0.jar:?]
        at com.atlassian.performance.tools.jvmtasks.api.TaskTimer.time(TaskTimer.kt:21) [virtual-users.jar:?]
        at com.atlassian.performance.tools.concurrency.api.TaskContextKt$submitWithLogContext$1.get(TaskContext.kt:24) [virtual-users.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```